# Generated by Django 4.2.7 on 2023-12-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_articles_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.CharField(default='Victor Kimani', max_length=64),
        ),
        migrations.AddField(
            model_name='articles',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='link',
            field=models.SlugField(blank=True, max_length=64),
        ),
    ]
